### ISSUE TITLE
Consuming queue error

### ISSUE THREAD

**Issue by say1j** [andreas-mausch/csgo-skinscreenshot#5]
Hi, trying to run your build, but getting next error:
```
C:\Users\admin\Desktop\testCSGO\csgo-skinscreenshot-master\client\csgo>py csgo-skinscreenshot.py
Traceback (most recent call last):
  File "csgo-skinscreenshot.py", line 44, in <module>
    messagequeue.start_consuming(callback)
  File "..\messagequeue.py", line 27, in start_consuming
    receiveMessage(channel, config.messagequeueName, callback)
  File "..\messagequeue.py", line 16, in receiveMessage
    channel.basic_consume(callback, queue)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pika\adapters\blocking_connection.py", line 1625, in basic_consume
    validators.require_string(queue, 'queue')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pika\validators.py", line 17, in require_string
    value,
TypeError: queue must be a str or unicode str, but got <function callback at 0x03155D20>
```
Queue in rabbitmq was created successfully, but got this error. 
Any idea how to fix?
Short running manual will be great too
And check your email from github, there you can find our offer :)

**Comment by andreas-mausch** [comment]
I can't tell right now, I would need to take a closer look.
In general it should be possible.

If you want to end up with a full-blown renderer, you also need to consider shaders and stickers.
